#! /usr/bin/env bash

#   Copyright 2021 nexryai
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


function urlencode {
  echo "$1" | nkf -WwMQ | sed 's/=$//g' | tr = % | tr -d '\n'
}


if [ -z "$1" ]; then
    echo "使用方法: ./cjp [变換レたい文章]"
    exit 1
fi

encoded=$(urlencode "$1")
cjp=$(curl -s "https://cjp.sbmr.in/api/raw/$encoded")

if [ $? != 0 ]; then
    echo "Error: curl terminated with error." 
    exit 1
fi

echo "$cjp"